### ISSUE TITLE
Upload to public maven repository

### ISSUE THREAD

**Issue by davidmichaelkarr** [jprante/jdbc-driver-csv#6]
To be more generally convenient, it would be best if this was released to a public maven repository, like jcenter and/or mavencentral.

**Comment by davidmichaelkarr** [comment]
Now I see that the problem is that you simply didn't add a section to the readme describing the GAV for the artifact.

**Comment by jprante** [comment]
Thanks for reporting. I pushed out a version 1.2.0 with updated Gradle, Gradle plugins, Maven Central artifact, and documentation.
